# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'О нас',
                'db_table': 'About',
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('maps', models.CharField(max_length=250, verbose_name='Карта')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.TextField(verbose_name='Телефоны')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'db_table': 'Contact',
                'verbose_name': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('years', models.CharField(max_length=250, verbose_name='Текущий год')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Главная',
                'db_table': 'Home',
                'verbose_name': 'Главная',
            },
        ),
    ]
