# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('archive', models.BooleanField(verbose_name='Архив')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('foto', models.ImageField(blank=True, upload_to='', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'db_table': 'Sale',
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акции',
            },
        ),
    ]
