# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='years',
        ),
        migrations.AddField(
            model_name='contact',
            name='years',
            field=models.CharField(default=2016, max_length=250, verbose_name='Текущий год'),
            preserve_default=False,
        ),
    ]
