# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 10:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160315_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=tinymce.models.HTMLField(verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
