# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 08:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160316_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
    ]
