# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160317_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('foto', models.ImageField(blank=True, upload_to='', verbose_name='Картинка')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'db_table': 'Service',
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услуги',
            },
        ),
    ]
