# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('social', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'Home',
            },
        ),
    ]
