# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=250)),
                ('ceni_na_remont', models.CharField(max_length=250)),
                ('zadat_vopros', models.CharField(max_length=250)),
                ('o_nas', models.CharField(max_length=250)),
                ('poleznoe', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
    ]
