# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 11:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160217_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2016, 2, 17, 11, 2, 55, 437768, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2016, 2, 17, 11, 3, 19, 668547, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2016, 2, 17, 11, 3, 38, 270345, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2016, 2, 17, 11, 3, 50, 368584, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
