# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 06:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160217_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
