# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 14:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160221_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'db_table': 'Uslugi',
            },
        ),
    ]
