# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 07:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_uslugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250, unique=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'db_table': 'SubMenu',
            },
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='ceni_na_remont',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='home',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='o_nas',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='poleznoe',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='zadat_vopros',
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Menu'),
        ),
    ]
