# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160223_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=250)),
                ('uslugi', models.CharField(max_length=250)),
                ('zadat_vopros', models.CharField(max_length=250)),
                ('o_nas', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Названия основных пунктов меню',
            },
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Контакты',
        ),
        migrations.AlterModelTable(
            name='home',
            table='Главная',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Группа своих пунктов меню',
        ),
        migrations.AlterModelTable(
            name='submenu',
            table='Свои пункты меню',
        ),
        migrations.AlterModelTable(
            name='uslugi',
            table='Цены на ремонт',
        ),
    ]
