# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160223_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Названия основных пунктов меню'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Группа для своих пунктов меню'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'Свои пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name': 'Цены на ремонт'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='home',
            table='Home',
        ),
        migrations.AlterModelTable(
            name='mainmenu',
            table='Mainmenu',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
        migrations.AlterModelTable(
            name='submenu',
            table='Submenu',
        ),
        migrations.AlterModelTable(
            name='uslugi',
            table='Uslugi',
        ),
    ]
