# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160223_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Названия основных пунктов меню', 'verbose_name_plural': 'Названия основных пунктов меню'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Группа для своих пунктов меню', 'verbose_name_plural': 'Группа для своих пунктов меню'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'Свои пункты меню', 'verbose_name_plural': 'Свои пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name': 'Цены на ремонт', 'verbose_name_plural': 'Цены на ремонт'},
        ),
    ]
