# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 17:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160223_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'db_table': 'Sale',
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='sale',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
