# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_onas_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='years',
            field=models.CharField(default=2010, max_length=250),
            preserve_default=False,
        ),
    ]
