# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 07:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_home_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('archive', models.BooleanField()),
                ('price', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'db_table': 'Product',
                'verbose_name': 'Товары',
            },
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.Submenu'),
        ),
    ]
